### ISSUE TITLE
Add minimum Requirements

### ISSUE THREAD

**Issue by regenrek** [tadejstanic/wp-hrm-webpack#1]
Hi,

maybe you should mention that you should at least (I think) Node 7.
I tried it yesterday with 6.5.0 and it failed. With 7.3.2 it's working fine!

Btw: Great work, was looking for an up to date example for hmr and wordpress!

Regards Kevin

**Comment by mydnicq** [comment]
Hi Kevin,

thx for pointing this out. I totally forgot to mention this. Now the Node v7 is a required engine.

Sorry that you had problems because of that.

Best, Tadej
